services:
  postgres:
    container_name: postgres_clothing
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      POSTGRES_DB: clothing_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d clothing_db"]
      interval: 1s
      timeout: 1s
      retries: 10

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: access
      MINIO_ROOT_PASSWORD: truesecret
      MINIO_REGION: us-east-1
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres-data:
    driver: local
  minio_data: